[package]
name = "ac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
id3 = "1.0"
walkdir = "2.3"
rodio = "0.17"
iced = {version = "0.12", features = ["smol"]}